// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: mp.proto

package pb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// MPServiceClient is the client API for MPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPServiceClient interface {
}

type mPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMPServiceClient(cc grpc.ClientConnInterface) MPServiceClient {
	return &mPServiceClient{cc}
}

// MPServiceServer is the server API for MPService service.
// All implementations must embed UnimplementedMPServiceServer
// for forward compatibility.
type MPServiceServer interface {
	mustEmbedUnimplementedMPServiceServer()
}

// UnimplementedMPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPServiceServer struct{}

func (UnimplementedMPServiceServer) mustEmbedUnimplementedMPServiceServer() {}
func (UnimplementedMPServiceServer) testEmbeddedByValue()                   {}

// UnsafeMPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPServiceServer will
// result in compilation errors.
type UnsafeMPServiceServer interface {
	mustEmbedUnimplementedMPServiceServer()
}

func RegisterMPServiceServer(s grpc.ServiceRegistrar, srv MPServiceServer) {
	// If the following call panics, it indicates UnimplementedMPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPService_ServiceDesc, srv)
}

// MPService_ServiceDesc is the grpc.ServiceDesc for MPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mp.MPService",
	HandlerType: (*MPServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "mp.proto",
}
