// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductsRequest_SortBy int32

const (
	ListProductsRequest_PRICE_LOW_TO_HIGH ListProductsRequest_SortBy = 0 // Menor a mayor precio
	ListProductsRequest_PRICE_HIGH_TO_LOW ListProductsRequest_SortBy = 1 // Mayor a menor precio
	ListProductsRequest_NAME_A_Z          ListProductsRequest_SortBy = 2 // Alfabético Ascendente
	ListProductsRequest_NAME_Z_A          ListProductsRequest_SortBy = 3 // Alfabético Descendente
)

// Enum value maps for ListProductsRequest_SortBy.
var (
	ListProductsRequest_SortBy_name = map[int32]string{
		0: "PRICE_LOW_TO_HIGH",
		1: "PRICE_HIGH_TO_LOW",
		2: "NAME_A_Z",
		3: "NAME_Z_A",
	}
	ListProductsRequest_SortBy_value = map[string]int32{
		"PRICE_LOW_TO_HIGH": 0,
		"PRICE_HIGH_TO_LOW": 1,
		"NAME_A_Z":          2,
		"NAME_Z_A":          3,
	}
)

func (x ListProductsRequest_SortBy) Enum() *ListProductsRequest_SortBy {
	p := new(ListProductsRequest_SortBy)
	*p = x
	return p
}

func (x ListProductsRequest_SortBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListProductsRequest_SortBy) Descriptor() protoreflect.EnumDescriptor {
	return file_product_proto_enumTypes[0].Descriptor()
}

func (ListProductsRequest_SortBy) Type() protoreflect.EnumType {
	return &file_product_proto_enumTypes[0]
}

func (x ListProductsRequest_SortBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListProductsRequest_SortBy.Descriptor instead.
func (ListProductsRequest_SortBy) EnumDescriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2, 0}
}

type Product struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code            string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price           float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	PrimaryImage    *string                `protobuf:"bytes,6,opt,name=primary_image,json=primaryImage,proto3,oneof" json:"primary_image,omitempty"`
	SecondaryImages []string               `protobuf:"bytes,7,rep,name=secondary_images,json=secondaryImages,proto3" json:"secondary_images,omitempty"`
	Stock           float32                `protobuf:"fixed32,8,opt,name=stock,proto3" json:"stock,omitempty"`
	Category        *Category              `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetPrimaryImage() string {
	if x != nil && x.PrimaryImage != nil {
		return *x.PrimaryImage
	}
	return ""
}

func (x *Product) GetSecondaryImages() []string {
	if x != nil {
		return x.SecondaryImages
	}
	return nil
}

func (x *Product) GetStock() float32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ProductDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	PrimaryImage  *string                `protobuf:"bytes,5,opt,name=primary_image,json=primaryImage,proto3,oneof" json:"primary_image,omitempty"`
	Stock         float32                `protobuf:"fixed32,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Category      *Category              `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDTO) Reset() {
	*x = ProductDTO{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDTO) ProtoMessage() {}

func (x *ProductDTO) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDTO.ProtoReflect.Descriptor instead.
func (*ProductDTO) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductDTO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProductDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDTO) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDTO) GetPrimaryImage() string {
	if x != nil && x.PrimaryImage != nil {
		return *x.PrimaryImage
	}
	return ""
}

func (x *ProductDTO) GetStock() float32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductDTO) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Page          int32                       `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                       `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Limit         int32                       `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	CategoryId    *int32                      `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Search        *string                     `protobuf:"bytes,5,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Sort          *ListProductsRequest_SortBy `protobuf:"varint,6,opt,name=sort,proto3,enum=product.ListProductsRequest_SortBy,oneof" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetCategoryId() int32 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *ListProductsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListProductsRequest) GetSort() ListProductsRequest_SortBy {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ListProductsRequest_PRICE_LOW_TO_HIGH
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductDTO          `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsResponse) GetProducts() []*ProductDTO {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SaveImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProdId          int64                  `protobuf:"varint,1,opt,name=prod_id,json=prodId,proto3" json:"prod_id,omitempty"`
	PrimaryImage    string                 `protobuf:"bytes,2,opt,name=primary_image,json=primaryImage,proto3" json:"primary_image,omitempty"`
	SecondaryImages []string               `protobuf:"bytes,3,rep,name=secondary_images,json=secondaryImages,proto3" json:"secondary_images,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveImageRequest) Reset() {
	*x = SaveImageRequest{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageRequest) ProtoMessage() {}

func (x *SaveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageRequest.ProtoReflect.Descriptor instead.
func (*SaveImageRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *SaveImageRequest) GetProdId() int64 {
	if x != nil {
		return x.ProdId
	}
	return 0
}

func (x *SaveImageRequest) GetPrimaryImage() string {
	if x != nil {
		return x.PrimaryImage
	}
	return ""
}

func (x *SaveImageRequest) GetSecondaryImages() []string {
	if x != nil {
		return x.SecondaryImages
	}
	return nil
}

type SaveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveImageResponse) Reset() {
	*x = SaveImageResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveImageResponse) ProtoMessage() {}

func (x *SaveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveImageResponse.ProtoReflect.Descriptor instead.
func (*SaveImageResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *SaveImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *ProductRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\x1a\x0ecategory.proto\"\xbb\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12(\n" +
	"\rprimary_image\x18\x06 \x01(\tH\x01R\fprimaryImage\x88\x01\x01\x12)\n" +
	"\x10secondary_images\x18\a \x03(\tR\x0fsecondaryImages\x12\x14\n" +
	"\x05stock\x18\b \x01(\x02R\x05stock\x12.\n" +
	"\bcategory\x18\t \x01(\v2\x12.category.CategoryR\bcategoryB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_primary_image\"\xdc\x01\n" +
	"\n" +
	"ProductDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12(\n" +
	"\rprimary_image\x18\x05 \x01(\tH\x00R\fprimaryImage\x88\x01\x01\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x02R\x05stock\x12.\n" +
	"\bcategory\x18\a \x01(\v2\x12.category.CategoryR\bcategoryB\x10\n" +
	"\x0e_primary_image\"\xd5\x02\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12$\n" +
	"\vcategory_id\x18\x04 \x01(\x05H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x1b\n" +
	"\x06search\x18\x05 \x01(\tH\x01R\x06search\x88\x01\x01\x12<\n" +
	"\x04sort\x18\x06 \x01(\x0e2#.product.ListProductsRequest.SortByH\x02R\x04sort\x88\x01\x01\"R\n" +
	"\x06SortBy\x12\x15\n" +
	"\x11PRICE_LOW_TO_HIGH\x10\x00\x12\x15\n" +
	"\x11PRICE_HIGH_TO_LOW\x10\x01\x12\f\n" +
	"\bNAME_A_Z\x10\x02\x12\f\n" +
	"\bNAME_Z_A\x10\x03B\x0e\n" +
	"\f_category_idB\t\n" +
	"\a_searchB\a\n" +
	"\x05_sort\"z\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.ProductDTOR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"'\n" +
	"\x11GetProductRequest\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"{\n" +
	"\x10SaveImageRequest\x12\x17\n" +
	"\aprod_id\x18\x01 \x01(\x03R\x06prodId\x12#\n" +
	"\rprimary_image\x18\x02 \x01(\tR\fprimaryImage\x12)\n" +
	"\x10secondary_images\x18\x03 \x03(\tR\x0fsecondaryImages\"-\n" +
	"\x11SaveImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x0eProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId2\x9d\x02\n" +
	"\x0eProductService\x12K\n" +
	"\fListProducts\x12\x1c.product.ListProductsRequest\x1a\x1d.product.ListProductsResponse\x12:\n" +
	"\n" +
	"GetProduct\x12\x1a.product.GetProductRequest\x1a\x10.product.Product\x12E\n" +
	"\fSaveUrlImage\x12\x19.product.SaveImageRequest\x1a\x1a.product.SaveImageResponse\x12;\n" +
	"\x0eGetProductByID\x12\x17.product.ProductRequest\x1a\x10.product.ProductB>Z<github.com/DanielChachagua/ecommerce-noagestion-protos/pb;pbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_product_proto_goTypes = []any{
	(ListProductsRequest_SortBy)(0), // 0: product.ListProductsRequest.SortBy
	(*Product)(nil),                 // 1: product.Product
	(*ProductDTO)(nil),              // 2: product.ProductDTO
	(*ListProductsRequest)(nil),     // 3: product.ListProductsRequest
	(*ListProductsResponse)(nil),    // 4: product.ListProductsResponse
	(*GetProductRequest)(nil),       // 5: product.GetProductRequest
	(*SaveImageRequest)(nil),        // 6: product.SaveImageRequest
	(*SaveImageResponse)(nil),       // 7: product.SaveImageResponse
	(*ProductRequest)(nil),          // 8: product.ProductRequest
	(*Category)(nil),                // 9: category.Category
}
var file_product_proto_depIdxs = []int32{
	9, // 0: product.Product.category:type_name -> category.Category
	9, // 1: product.ProductDTO.category:type_name -> category.Category
	0, // 2: product.ListProductsRequest.sort:type_name -> product.ListProductsRequest.SortBy
	2, // 3: product.ListProductsResponse.products:type_name -> product.ProductDTO
	3, // 4: product.ProductService.ListProducts:input_type -> product.ListProductsRequest
	5, // 5: product.ProductService.GetProduct:input_type -> product.GetProductRequest
	6, // 6: product.ProductService.SaveUrlImage:input_type -> product.SaveImageRequest
	8, // 7: product.ProductService.GetProductByID:input_type -> product.ProductRequest
	4, // 8: product.ProductService.ListProducts:output_type -> product.ListProductsResponse
	1, // 9: product.ProductService.GetProduct:output_type -> product.Product
	7, // 10: product.ProductService.SaveUrlImage:output_type -> product.SaveImageResponse
	1, // 11: product.ProductService.GetProductByID:output_type -> product.Product
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	file_category_proto_init()
	file_product_proto_msgTypes[0].OneofWrappers = []any{}
	file_product_proto_msgTypes[1].OneofWrappers = []any{}
	file_product_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		EnumInfos:         file_product_proto_enumTypes,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
