// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tenant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingTenant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Logo           string                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	FrontPage      string                 `protobuf:"bytes,3,opt,name=front_page,json=frontPage,proto3" json:"front_page,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Slogan         string                 `protobuf:"bytes,5,opt,name=slogan,proto3" json:"slogan,omitempty"`
	PrimaryColor   string                 `protobuf:"bytes,6,opt,name=primary_color,json=primaryColor,proto3" json:"primary_color,omitempty"`
	SecondaryColor string                 `protobuf:"bytes,7,opt,name=secondary_color,json=secondaryColor,proto3" json:"secondary_color,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SettingTenant) Reset() {
	*x = SettingTenant{}
	mi := &file_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingTenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingTenant) ProtoMessage() {}

func (x *SettingTenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingTenant.ProtoReflect.Descriptor instead.
func (*SettingTenant) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *SettingTenant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SettingTenant) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *SettingTenant) GetFrontPage() string {
	if x != nil {
		return x.FrontPage
	}
	return ""
}

func (x *SettingTenant) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SettingTenant) GetSlogan() string {
	if x != nil {
		return x.Slogan
	}
	return ""
}

func (x *SettingTenant) GetPrimaryColor() string {
	if x != nil {
		return x.PrimaryColor
	}
	return ""
}

func (x *SettingTenant) GetSecondaryColor() string {
	if x != nil {
		return x.SecondaryColor
	}
	return ""
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *Tenant) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Tenant) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Tenant) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Identifier    string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	SettingTenant *SettingTenant         `protobuf:"bytes,7,opt,name=setting_tenant,json=settingTenant,proto3" json:"setting_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *TenantResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *TenantResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TenantResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *TenantResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantResponse) GetSettingTenant() *SettingTenant {
	if x != nil {
		return x.SettingTenant
	}
	return nil
}

type TenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRequest) Reset() {
	*x = TenantRequest{}
	mi := &file_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRequest) ProtoMessage() {}

func (x *TenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRequest.ProtoReflect.Descriptor instead.
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *TenantRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{4}
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type TenantRequestImageSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoUuid      *string                `protobuf:"bytes,1,opt,name=logo_uuid,json=logoUuid,proto3,oneof" json:"logo_uuid,omitempty"`
	FrontPageUuid *string                `protobuf:"bytes,2,opt,name=front_page_uuid,json=frontPageUuid,proto3,oneof" json:"front_page_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRequestImageSetting) Reset() {
	*x = TenantRequestImageSetting{}
	mi := &file_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRequestImageSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRequestImageSetting) ProtoMessage() {}

func (x *TenantRequestImageSetting) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRequestImageSetting.ProtoReflect.Descriptor instead.
func (*TenantRequestImageSetting) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *TenantRequestImageSetting) GetLogoUuid() string {
	if x != nil && x.LogoUuid != nil {
		return *x.LogoUuid
	}
	return ""
}

func (x *TenantRequestImageSetting) GetFrontPageUuid() string {
	if x != nil && x.FrontPageUuid != nil {
		return *x.FrontPageUuid
	}
	return ""
}

type TenantUpdateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogoUuid      *string                `protobuf:"bytes,1,opt,name=logo_uuid,json=logoUuid,proto3,oneof" json:"logo_uuid,omitempty"`
	FrontPageUuid *string                `protobuf:"bytes,2,opt,name=front_page_uuid,json=frontPageUuid,proto3,oneof" json:"front_page_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUpdateImageResponse) Reset() {
	*x = TenantUpdateImageResponse{}
	mi := &file_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUpdateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUpdateImageResponse) ProtoMessage() {}

func (x *TenantUpdateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUpdateImageResponse.ProtoReflect.Descriptor instead.
func (*TenantUpdateImageResponse) Descriptor() ([]byte, []int) {
	return file_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *TenantUpdateImageResponse) GetLogoUuid() string {
	if x != nil && x.LogoUuid != nil {
		return *x.LogoUuid
	}
	return ""
}

func (x *TenantUpdateImageResponse) GetFrontPageUuid() string {
	if x != nil && x.FrontPageUuid != nil {
		return *x.FrontPageUuid
	}
	return ""
}

var File_tenant_proto protoreflect.FileDescriptor

const file_tenant_proto_rawDesc = "" +
	"\n" +
	"\ftenant.proto\x12\x06tenant\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x01\n" +
	"\rSettingTenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04logo\x18\x02 \x01(\tR\x04logo\x12\x1d\n" +
	"\n" +
	"front_page\x18\x03 \x01(\tR\tfrontPage\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06slogan\x18\x05 \x01(\tR\x06slogan\x12#\n" +
	"\rprimary_color\x18\x06 \x01(\tR\fprimaryColor\x12'\n" +
	"\x0fsecondary_color\x18\a \x01(\tR\x0esecondaryColor\"\x95\x01\n" +
	"\x06Tenant\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12?\n" +
	"\n" +
	"expiration\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"expiration\x88\x01\x01B\r\n" +
	"\v_expiration\"\xd8\x01\n" +
	"\x0eTenantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12<\n" +
	"\x0esetting_tenant\x18\a \x01(\v2\x15.tenant.SettingTenantR\rsettingTenant\"/\n" +
	"\rTenantRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"\x14\n" +
	"\x12ListTenantsRequest\"?\n" +
	"\x13ListTenantsResponse\x12(\n" +
	"\atenants\x18\x01 \x03(\v2\x0e.tenant.TenantR\atenants\"\x8c\x01\n" +
	"\x19TenantRequestImageSetting\x12 \n" +
	"\tlogo_uuid\x18\x01 \x01(\tH\x00R\blogoUuid\x88\x01\x01\x12+\n" +
	"\x0ffront_page_uuid\x18\x02 \x01(\tH\x01R\rfrontPageUuid\x88\x01\x01B\f\n" +
	"\n" +
	"_logo_uuidB\x12\n" +
	"\x10_front_page_uuid\"\x8c\x01\n" +
	"\x19TenantUpdateImageResponse\x12 \n" +
	"\tlogo_uuid\x18\x01 \x01(\tH\x00R\blogoUuid\x88\x01\x01\x12+\n" +
	"\x0ffront_page_uuid\x18\x02 \x01(\tH\x01R\rfrontPageUuid\x88\x01\x01B\f\n" +
	"\n" +
	"_logo_uuidB\x12\n" +
	"\x10_front_page_uuid2\xff\x01\n" +
	"\rTenantService\x12F\n" +
	"\vListTenants\x12\x1a.tenant.ListTenantsRequest\x1a\x1b.tenant.ListTenantsResponse\x12D\n" +
	"\x13TenantGetIdentifier\x12\x15.tenant.TenantRequest\x1a\x16.tenant.TenantResponse\x12`\n" +
	"\x18TenantUpdateImageSetting\x12!.tenant.TenantRequestImageSetting\x1a!.tenant.TenantUpdateImageResponseB>Z<github.com/DanielChachagua/ecommerce-noagestion-protos/pb;pbb\x06proto3"

var (
	file_tenant_proto_rawDescOnce sync.Once
	file_tenant_proto_rawDescData []byte
)

func file_tenant_proto_rawDescGZIP() []byte {
	file_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_proto_rawDesc), len(file_tenant_proto_rawDesc)))
	})
	return file_tenant_proto_rawDescData
}

var file_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tenant_proto_goTypes = []any{
	(*SettingTenant)(nil),             // 0: tenant.SettingTenant
	(*Tenant)(nil),                    // 1: tenant.Tenant
	(*TenantResponse)(nil),            // 2: tenant.TenantResponse
	(*TenantRequest)(nil),             // 3: tenant.TenantRequest
	(*ListTenantsRequest)(nil),        // 4: tenant.ListTenantsRequest
	(*ListTenantsResponse)(nil),       // 5: tenant.ListTenantsResponse
	(*TenantRequestImageSetting)(nil), // 6: tenant.TenantRequestImageSetting
	(*TenantUpdateImageResponse)(nil), // 7: tenant.TenantUpdateImageResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_tenant_proto_depIdxs = []int32{
	8, // 0: tenant.Tenant.expiration:type_name -> google.protobuf.Timestamp
	0, // 1: tenant.TenantResponse.setting_tenant:type_name -> tenant.SettingTenant
	1, // 2: tenant.ListTenantsResponse.tenants:type_name -> tenant.Tenant
	4, // 3: tenant.TenantService.ListTenants:input_type -> tenant.ListTenantsRequest
	3, // 4: tenant.TenantService.TenantGetIdentifier:input_type -> tenant.TenantRequest
	6, // 5: tenant.TenantService.TenantUpdateImageSetting:input_type -> tenant.TenantRequestImageSetting
	5, // 6: tenant.TenantService.ListTenants:output_type -> tenant.ListTenantsResponse
	2, // 7: tenant.TenantService.TenantGetIdentifier:output_type -> tenant.TenantResponse
	7, // 8: tenant.TenantService.TenantUpdateImageSetting:output_type -> tenant.TenantUpdateImageResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tenant_proto_init() }
func file_tenant_proto_init() {
	if File_tenant_proto != nil {
		return
	}
	file_tenant_proto_msgTypes[1].OneofWrappers = []any{}
	file_tenant_proto_msgTypes[6].OneofWrappers = []any{}
	file_tenant_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_proto_rawDesc), len(file_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_proto_depIdxs,
		MessageInfos:      file_tenant_proto_msgTypes,
	}.Build()
	File_tenant_proto = out.File
	file_tenant_proto_goTypes = nil
	file_tenant_proto_depIdxs = nil
}
